### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by Technew94** [albert-ying/ohmyggplot#1]
Installing package into ‘/home/shuxin/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package ‘ohmyggplot’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘ggplot’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘ohmyggplot’

If theres a '2' missed in the package make file?

**Comment by albert-ying** [comment]
Thank you! It is now fixed.
